---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    BASE_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/
    IGNORE_KINESIS: True
    LOG_LEVEL: info
ENCRYPTED_VARIABLES:
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCu20jxZpTC9cf9V8QIBEIAmt4TZJ7JuFQ1C845HxG8wAXzC7SFHkMNe4U6rKlD1twveXygfiQc=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGgwZgYJKoZIhvcNAQcGoFkwVwIBADBSBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFl5tITDZVWhuAo4bwIBEIAlAJz8CVF81vrNuPneSCNYOjts4HmiVgF4kyebQJSWxKPTFQ0Elw==
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAG4wbAYJKoZIhvcNAQcGoF8wXQIBADBYBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDznllIwMMYsJenLeQIBEIArfb3EgodbR+chRZD++wfccciwA8X1IWxxyCoY3dOKhE+cEKagtUS0DQuSAg==
...