---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    BASE_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/
    KINESIS_BATCH_SIZE: 500
    LOG_LEVEL: info
ENCRYPTED_VARIABLES:
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDL6zq0QQYBhdW4rz8gIBEIApxucxIVAb1Ec4uHUAwxRZcvC8OAZxuj/oJAkhCPh8sPJJ08w3ECoXoKk=
    SIERRA_DB_USER:
    SIERRA_DB_PASSWORD:
    BASE_KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAI0wgYoGCSqGSIb3DQEHBqB9MHsCAQAwdgYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAz8ukY2D7pVVOoXnTECARCASQDB/0Mrin58TIBxXljGVexKh8wi5JNCofBenCn3zWEwJBDCohwFJbADWTFRatwTathDUW/8JEiP6v9E4XLVdS4Olqw/4+EdP5I=
...